# Generating SBOM using Syft

name: Generating SBOM using Syft

on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    - name: test
      run: mvn package
      if: steps.extract_branch.outputs.branch == 'Dev'
    - name: Build docker image 
      working-directory: .
      run: |
            docker build -t  ghcr.io/kirtighugtyal6/testfile/springapp:latest .
      
    - name: Package Frontend
      run: |
        docker build -t test-image .
        
    - uses: anchore/sbom-action@v0
      with: 
        image: test-image:latest
        format: cyclonedx
        artifact-name: report.cyclonedx
        output-file: ./report.cyclonedx
        
